name: AuctionMaster
authors: [qKing12, SedatTR, rudde]
version: 5.0
main: me.qKing12.AuctionMaster.AuctionMaster
description: The best & free auction made by qKing12#1918, continued by SedatTR#8666 with love...
website: https://discord.gg/nchk86TKMT
api-version: "1.13"
softdepend: [LiteBans, CustomEconomy, Citizens, Vault, PlayerPoints, TokenManager, PlaceholderAPI, Skript, ProtocolLib, HeadDatabase]

commands:
  auction:
    aliases: [ah, auctions, auctionhouse, ahouse]
    description: Use this command to open the auction menu.
  ahview:
    description: View an auction.
  ahadmin:
    description: Use this command for admin things.